//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 09:19:26 PM EDT 
//


package cz.datalite.ares.ws.ares.basic;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Data upravená dle ARES (tabulka k_podnet)
 * 
 * <p>Java class for aceu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aceu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="K_konkurz" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}k_konkurz"/&gt;
 *         &lt;element name="Poradi" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="DV_podnetu" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="K_ukonu_podnetu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}kod_ukonu_podnetu"/&gt;
 *         &lt;element name="Priznak_usneseni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}ano_ne"/&gt;
 *         &lt;element name="Radky_textu_usneseni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}radky_textu_usneseni" minOccurs="0"/&gt;
 *         &lt;element name="J_souboru_s_usnesenim" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis" minOccurs="0"/&gt;
 *         &lt;element name="Spravce_konkurzu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}spravce_konkurzu_CEU" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Priznaky" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}priznaky_CEU"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aceu", propOrder = {
    "kKonkurz",
    "poradi",
    "dvPodnetu",
    "kUkonuPodnetu",
    "priznakUsneseni",
    "radkyTextuUsneseni",
    "jSouboruSUsnesenim",
    "spravceKonkurzu",
    "priznaky"
})
public class Aceu {

    @XmlElement(name = "K_konkurz", required = true)
    protected KKonkurz kKonkurz;
    @XmlElement(name = "Poradi")
    protected short poradi;
    @XmlElement(name = "DV_podnetu", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dvPodnetu;
    @XmlElement(name = "K_ukonu_podnetu")
    protected byte kUkonuPodnetu;
    @XmlElement(name = "Priznak_usneseni", required = true)
    protected String priznakUsneseni;
    @XmlElement(name = "Radky_textu_usneseni")
    protected RadkyTextuUsneseni radkyTextuUsneseni;
    @XmlElement(name = "J_souboru_s_usnesenim")
    protected String jSouboruSUsnesenim;
    @XmlElement(name = "Spravce_konkurzu")
    protected List<SpravceKonkurzuCEU> spravceKonkurzu;
    @XmlElement(name = "Priznaky", required = true)
    protected String priznaky;

    /**
     * Gets the value of the kKonkurz property.
     * 
     * @return
     *     possible object is
     *     {@link KKonkurz }
     *     
     */
    public KKonkurz getKKonkurz() {
        return kKonkurz;
    }

    /**
     * Sets the value of the kKonkurz property.
     * 
     * @param value
     *     allowed object is
     *     {@link KKonkurz }
     *     
     */
    public void setKKonkurz(KKonkurz value) {
        this.kKonkurz = value;
    }

    /**
     * Gets the value of the poradi property.
     * 
     */
    public short getPoradi() {
        return poradi;
    }

    /**
     * Sets the value of the poradi property.
     * 
     */
    public void setPoradi(short value) {
        this.poradi = value;
    }

    /**
     * Gets the value of the dvPodnetu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDVPodnetu() {
        return dvPodnetu;
    }

    /**
     * Sets the value of the dvPodnetu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDVPodnetu(XMLGregorianCalendar value) {
        this.dvPodnetu = value;
    }

    /**
     * Gets the value of the kUkonuPodnetu property.
     * 
     */
    public byte getKUkonuPodnetu() {
        return kUkonuPodnetu;
    }

    /**
     * Sets the value of the kUkonuPodnetu property.
     * 
     */
    public void setKUkonuPodnetu(byte value) {
        this.kUkonuPodnetu = value;
    }

    /**
     * Gets the value of the priznakUsneseni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriznakUsneseni() {
        return priznakUsneseni;
    }

    /**
     * Sets the value of the priznakUsneseni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriznakUsneseni(String value) {
        this.priznakUsneseni = value;
    }

    /**
     * Gets the value of the radkyTextuUsneseni property.
     * 
     * @return
     *     possible object is
     *     {@link RadkyTextuUsneseni }
     *     
     */
    public RadkyTextuUsneseni getRadkyTextuUsneseni() {
        return radkyTextuUsneseni;
    }

    /**
     * Sets the value of the radkyTextuUsneseni property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadkyTextuUsneseni }
     *     
     */
    public void setRadkyTextuUsneseni(RadkyTextuUsneseni value) {
        this.radkyTextuUsneseni = value;
    }

    /**
     * Gets the value of the jSouboruSUsnesenim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJSouboruSUsnesenim() {
        return jSouboruSUsnesenim;
    }

    /**
     * Sets the value of the jSouboruSUsnesenim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJSouboruSUsnesenim(String value) {
        this.jSouboruSUsnesenim = value;
    }

    /**
     * Gets the value of the spravceKonkurzu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spravceKonkurzu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpravceKonkurzu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpravceKonkurzuCEU }
     * 
     * 
     */
    public List<SpravceKonkurzuCEU> getSpravceKonkurzu() {
        if (spravceKonkurzu == null) {
            spravceKonkurzu = new ArrayList<SpravceKonkurzuCEU>();
        }
        return this.spravceKonkurzu;
    }

    /**
     * Gets the value of the priznaky property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriznaky() {
        return priznaky;
    }

    /**
     * Sets the value of the priznaky property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriznaky(String value) {
        this.priznaky = value;
    }

}
