//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 09:19:26 PM EDT 
//


package cz.datalite.ares.ws.ares.basic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifické údaje o konkurzu
 * 
 * <p>Java class for konkurz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="konkurz"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KVZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}udaje_KVZ"/&gt;
 *         &lt;element name="SKP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}spravce" minOccurs="0"/&gt;
 *         &lt;element name="ZAS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}spravce" minOccurs="0"/&gt;
 *         &lt;element name="ZVS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}spravce" minOccurs="0"/&gt;
 *         &lt;element name="PRS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}spravce" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "konkurz", propOrder = {
    "kvz",
    "skp",
    "zas",
    "zvs",
    "prs"
})
public class Konkurz {

    @XmlElement(name = "KVZ", required = true)
    protected UdajeKVZ kvz;
    @XmlElement(name = "SKP")
    protected Spravce skp;
    @XmlElement(name = "ZAS")
    protected Spravce zas;
    @XmlElement(name = "ZVS")
    protected Spravce zvs;
    @XmlElement(name = "PRS")
    protected Spravce prs;

    /**
     * Gets the value of the kvz property.
     * 
     * @return
     *     possible object is
     *     {@link UdajeKVZ }
     *     
     */
    public UdajeKVZ getKVZ() {
        return kvz;
    }

    /**
     * Sets the value of the kvz property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdajeKVZ }
     *     
     */
    public void setKVZ(UdajeKVZ value) {
        this.kvz = value;
    }

    /**
     * Gets the value of the skp property.
     * 
     * @return
     *     possible object is
     *     {@link Spravce }
     *     
     */
    public Spravce getSKP() {
        return skp;
    }

    /**
     * Sets the value of the skp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spravce }
     *     
     */
    public void setSKP(Spravce value) {
        this.skp = value;
    }

    /**
     * Gets the value of the zas property.
     * 
     * @return
     *     possible object is
     *     {@link Spravce }
     *     
     */
    public Spravce getZAS() {
        return zas;
    }

    /**
     * Sets the value of the zas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spravce }
     *     
     */
    public void setZAS(Spravce value) {
        this.zas = value;
    }

    /**
     * Gets the value of the zvs property.
     * 
     * @return
     *     possible object is
     *     {@link Spravce }
     *     
     */
    public Spravce getZVS() {
        return zvs;
    }

    /**
     * Sets the value of the zvs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spravce }
     *     
     */
    public void setZVS(Spravce value) {
        this.zvs = value;
    }

    /**
     * Gets the value of the prs property.
     * 
     * @return
     *     possible object is
     *     {@link Spravce }
     *     
     */
    public Spravce getPRS() {
        return prs;
    }

    /**
     * Sets the value of the prs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spravce }
     *     
     */
    public void setPRS(Spravce value) {
        this.prs = value;
    }

}
