//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 09:19:26 PM EDT 
//


package cz.datalite.ares.ws.ares.basic;

import javax.xml.bind.annotation.*;


/**
 * Právní forma včetně popisných položek
 * 
 * <p>Java class for pravni_forma_RZP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pravni_forma_RZP"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="KPF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}kod_pravni_formy"/&gt;
 *         &lt;element name="NPF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_pravni_formy" minOccurs="0"/&gt;
 *         &lt;element name="ZPF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}zkraceny_nazev_PF" minOccurs="0"/&gt;
 *         &lt;element name="PFO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}pf_osoba" minOccurs="0"/&gt;
 *         &lt;element name="TZU" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}tzu_osoba" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pravni_forma_RZP", propOrder = {
    "kpf",
    "npf",
    "zpf",
    "pfo",
    "tzu"
})
public class PravniFormaRZP {

    @XmlElement(name = "KPF")
    protected short kpf;
    @XmlElement(name = "NPF")
    protected String npf;
    @XmlElement(name = "ZPF")
    protected String zpf;
    @XmlElement(name = "PFO")
    @XmlSchemaType(name = "string")
    protected PfOsoba pfo;
    @XmlElement(name = "TZU")
    @XmlSchemaType(name = "string")
    protected TzuOsoba tzu;

    /**
     * Gets the value of the kpf property.
     * 
     */
    public short getKPF() {
        return kpf;
    }

    /**
     * Sets the value of the kpf property.
     * 
     */
    public void setKPF(short value) {
        this.kpf = value;
    }

    /**
     * Gets the value of the npf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPF() {
        return npf;
    }

    /**
     * Sets the value of the npf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPF(String value) {
        this.npf = value;
    }

    /**
     * Gets the value of the zpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZPF() {
        return zpf;
    }

    /**
     * Sets the value of the zpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZPF(String value) {
        this.zpf = value;
    }

    /**
     * Gets the value of the pfo property.
     * 
     * @return
     *     possible object is
     *     {@link PfOsoba }
     *     
     */
    public PfOsoba getPFO() {
        return pfo;
    }

    /**
     * Sets the value of the pfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PfOsoba }
     *     
     */
    public void setPFO(PfOsoba value) {
        this.pfo = value;
    }

    /**
     * Gets the value of the tzu property.
     * 
     * @return
     *     possible object is
     *     {@link TzuOsoba }
     *     
     */
    public TzuOsoba getTZU() {
        return tzu;
    }

    /**
     * Sets the value of the tzu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TzuOsoba }
     *     
     */
    public void setTZU(TzuOsoba value) {
        this.tzu = value;
    }

}
