//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 09:19:26 PM EDT 
//


package cz.datalite.ares.ws.ares.basic;

import javax.xml.bind.annotation.*;


/**
 * S subjektu: Aktivní / Zaniklý a atributy KKZ, VY, ZAM, LI
 * 
 * <p>Java class for stav complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stav"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SSU" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_subjektu" minOccurs="0"/&gt;
 *         &lt;element name="KKZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_KVZ"/&gt;
 *         &lt;element name="VY" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_KVZ"/&gt;
 *         &lt;element name="ZAM" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_KVZ"/&gt;
 *         &lt;element name="LI" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_KVZ"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stav", propOrder = {
    "ssu",
    "kkz",
    "vy",
    "zam",
    "li"
})
public class Stav {

    @XmlElement(name = "SSU")
    @XmlSchemaType(name = "string")
    protected StavSubjektu ssu;
    @XmlElement(name = "KKZ", required = true)
    protected StavKVZ kkz;
    @XmlElement(name = "VY", required = true)
    protected StavKVZ vy;
    @XmlElement(name = "ZAM", required = true)
    protected StavKVZ zam;
    @XmlElement(name = "LI", required = true)
    protected StavKVZ li;

    /**
     * Gets the value of the ssu property.
     * 
     * @return
     *     possible object is
     *     {@link StavSubjektu }
     *     
     */
    public StavSubjektu getSSU() {
        return ssu;
    }

    /**
     * Sets the value of the ssu property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavSubjektu }
     *     
     */
    public void setSSU(StavSubjektu value) {
        this.ssu = value;
    }

    /**
     * Gets the value of the kkz property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getKKZ() {
        return kkz;
    }

    /**
     * Sets the value of the kkz property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setKKZ(StavKVZ value) {
        this.kkz = value;
    }

    /**
     * Gets the value of the vy property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getVY() {
        return vy;
    }

    /**
     * Sets the value of the vy property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setVY(StavKVZ value) {
        this.vy = value;
    }

    /**
     * Gets the value of the zam property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getZAM() {
        return zam;
    }

    /**
     * Sets the value of the zam property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setZAM(StavKVZ value) {
        this.zam = value;
    }

    /**
     * Gets the value of the li property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getLI() {
        return li;
    }

    /**
     * Sets the value of the li property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setLI(StavKVZ value) {
        this.li = value;
    }

}
