//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 09:19:26 PM EDT 
//


package cz.datalite.ares.ws.ares.basic;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for udalost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="udalost"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="POD" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="TDA" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}text" minOccurs="0"/&gt;
 *         &lt;element name="TZM" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}typ_zmeny" minOccurs="0"/&gt;
 *         &lt;element name="US" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ID_usneseni" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="S" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "udalost", propOrder = {
    "pod",
    "tda",
    "tzm",
    "us",
    "idUsneseni",
    "s"
})
public class Udalost {

    @XmlElement(name = "POD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pod;
    @XmlElement(name = "TDA")
    protected String tda;
    @XmlElement(name = "TZM")
    protected TypZmeny tzm;
    @XmlElement(name = "US")
    protected Boolean us;
    @XmlElement(name = "ID_usneseni")
    protected BigInteger idUsneseni;
    @XmlElement(name = "S")
    protected Stav s;

    /**
     * Gets the value of the pod property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPOD() {
        return pod;
    }

    /**
     * Sets the value of the pod property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPOD(XMLGregorianCalendar value) {
        this.pod = value;
    }

    /**
     * Gets the value of the tda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTDA() {
        return tda;
    }

    /**
     * Sets the value of the tda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTDA(String value) {
        this.tda = value;
    }

    /**
     * Gets the value of the tzm property.
     * 
     * @return
     *     possible object is
     *     {@link TypZmeny }
     *     
     */
    public TypZmeny getTZM() {
        return tzm;
    }

    /**
     * Sets the value of the tzm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypZmeny }
     *     
     */
    public void setTZM(TypZmeny value) {
        this.tzm = value;
    }

    /**
     * Gets the value of the us property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUS() {
        return us;
    }

    /**
     * Sets the value of the us property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUS(Boolean value) {
        this.us = value;
    }

    /**
     * Gets the value of the idUsneseni property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIDUsneseni() {
        return idUsneseni;
    }

    /**
     * Sets the value of the idUsneseni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDUsneseni(BigInteger value) {
        this.idUsneseni = value;
    }

    /**
     * Gets the value of the s property.
     * 
     * @return
     *     possible object is
     *     {@link Stav }
     *     
     */
    public Stav getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stav }
     *     
     */
    public void setS(Stav value) {
        this.s = value;
    }

}
